# Generated by Django 3.2.7 on 2021-10-12 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tempapp1', '0002_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
